import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex min-h-screen h-full bg-gradient-to-tl from-black via-zinc-600/20 to-black ">
          <div className="invisible xl:visible sidebar fixed bottom-0 top-0 lg:left-0 p-2 w-[290px] overflow-y-auto text-center pt-12">
            <a
              href="#welcome"
              className="p-2.5 mt-3 flex items-center rounded-md px-4 duration-300 cursor-pointer hover:bg-blue-500 text-white"
            >
              <span className="text-[15px] ml-4 text-gray-200 font-bold">
                Welcome
              </span>
            </a>
            <a
              href="#my-work"
              className="p-2.5 mt-3 flex items-center rounded-md px-4 duration-300 cursor-pointer hover:bg-blue-500 text-white"
            >
              <span className="text-[15px] ml-4 text-gray-200 font-bold">
                My Work
              </span>
            </a>
            <a
              href="#tech-stack"
              className="p-2.5 mt-3 flex items-center rounded-md px-4 duration-300 cursor-pointer hover:bg-blue-500 text-white"
            >
              <span className="text-[15px] ml-4 text-gray-200 font-bold">
                Tech Stack
              </span>
            </a>
            <a
              href="#contact"
              className="p-2.5 mt-3 flex items-center rounded-md px-4 duration-300 cursor-pointer hover:bg-blue-500 text-white"
            >
              <span className="text-[15px] ml-4 text-gray-200 font-bold">
                Contact
              </span>
            </a>
          </div>
          <div className="w-1/12 xl:grow"></div>

          <div className="grow p-12 xl:w-1/2 max-w-4xl">{children}</div>
          <div className="w-1/12 xl:grow"></div>
        </div>
      </body>
    </html>
  );
}
